= Wut - A simple i18n pack

== Disclaimer

This library is a work-in-progress, and definitely not ready for production. Anything can chance, tests need improvement and there are still no benchmarks.

This library's aim is to have a simple to use and upkeep i18n library. If possible, I'll try to prepare integrations with any popular validation frameworks and whatever else looks to be useful.

== Install

[source,bash]
go get github.com/borislav-rangelov/wut

== Usage

Firstly, prepare some translations
[source,toml]
----
# resources/i18n/en.toml
language = "en"

[display]
hello = "Hello"
hello_name = 'Hello, {{ .Name }}' # standard text/template format
----

[source,toml]
----
# resources/i18n/es.toml
language = "es"
fallback = "en"

[display]
hello = "Hola"
hello_template = '{{ get "display.hello" }}, {{ .Name }}' #Keep in mind that 'get' will use the language of the template it was being used in as the starting one and needs the default lang factory to be set up.
----

Then, use the `wut.Setup()` builder to configure the library (easiest approach).

[source,go]
--
package main

import (
    "fmt"
    "github.com/borislav-rangelov/wut"
)

type User struct{
	Name string
}

func main() {
    err := wut.Setup().
	    AddFiles("resources/i18n/en.toml",
			"resources/i18n/es.toml").
		AsDefault()

	if err != nil {
		panic(err)
	}

	english := wut.Lang("en")
	spanish := wut.Lang("es")

	// "Hello"
	fmt.Println(english.Get("display.hello").Txt)
	// "Hola"
	fmt.Println(spanish.Get("display.hello").Txt)

	msg := english.Get("display.bye")
	// ""
	fmt.Println(msg.Txt)
	// "Bye"
	fmt.Println(msg.Or("Bye"))

	user := User{Name: "Wut"}
	templatedMsg := english.Get("display.hello_name", user)

	// "Hello, Wut"
	fmt.Println(templatedMsg.Txt)
}
--

Easiest config is to use `wut.Setup().AsDefault()` in the main application.
When testing, you can use `wut.SetDefaultFactory()` to prepare something for the test. If I have the time, I'll try to make a version, which is easier to test with.

If there are issues, pass in the `LangFactory`, or `LangSource` to the specific methods.
